[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "qsnow"
version = "0.1.1"
description = "qSNOW (Simulated Noise Orchestration Workflow) - orchestrate multiple logicals across a grid/chip of qubits."
requires-python = ">=3.14"
dependencies = [
    "numpy",
    "stim",
    "sinter",
    "plotly",
    "nbformat",
    "shapely",
    "scipy",
    "pymatching",
    "rich"
]

[project.optional-dependencies]
dev = ["ipykernel", "ruff"]
test = ["pytest", "pytest-cov", "kaleido"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
omit = [
    "*/__init__.py",
    "tests/*"
]
