"""
Noise distributions: the recipes that produce a chip's physical-error-rate landscape.

A `NoiseDistribution` holds the parameters of the distribution it models (and a seed),
and produces that distribution for a chip's sites (`sites(chip)`) and couplers
(`couplers(chip)`) as `NoiseProfile` maps. The object itself is what `Chip.spec`
records and the flake format serializes, so a saved landscape is regenerated by
rebuilding the object and calling it again - not by replaying a name-and-dict.

Hierarchy:

    NoiseDistribution (abstract)          recipe + sites + couplers
    ├── Uniform                           constant p
    ├── Custom                            explicit maps
    └── GaussianFieldDistribution         field -> reshape pipeline, cross-correlation
        ├── RandomUniform                 iid draws, uniform marginal
        ├── RandomGaussian                iid draws, truncated-normal marginal
        └── ContourDistribution           adds `slope`; field = box-averaged white noise
            ├── NormalContour             legacy soft-clip reshape
            └── SkewContour               Pearson III reshape

The four sampled distributions share one pipeline, described stage by stage in
`writeups/noise_generation_walkthrough.tex`. Subclasses register under the record name
their landscapes are labelled with (`register_distribution`), so captions, HTML
subtitles and flakes read unchanged.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field, fields as dataclass_fields
from statistics import mean
from typing import TYPE_CHECKING, Any, ClassVar, Dict, Iterable, Optional, Tuple, Type, TypeVar

import numpy as np
from numpy.random import SeedSequence, default_rng
from scipy.stats import truncnorm, uniform

from ..models import Coord, CouplerKey, NoiseProfile
from .fields import (
    Center,
    blend_latents,
    correlated_gaussian_field,
    iid_gaussian_field,
    normal_scores,
    p_bounds,
    quantile_map,
    scale_gaussian_contour,
    skewed_target,
)

if TYPE_CHECKING:
    from ..chip import Chip

__all__ = [
    "NoiseDistribution",
    "GaussianFieldDistribution",
    "ContourDistribution",
    "Uniform",
    "Custom",
    "RandomUniform",
    "RandomGaussian",
    "NormalContour",
    "SkewContour",
    "register_distribution",
    "distribution_from_dict",
    "as_profile",
    "profiles",
]

_REGISTRY: Dict[str, Type["NoiseDistribution"]] = {}

# Generic so a decorated class keeps its own type: annotating the decorator as returning
# `Type[NoiseDistribution]` would make static checkers see every subclass as the base,
# whose constructor is just `(*, seed=None)`.
_D = TypeVar("_D", bound=Type["NoiseDistribution"])


def register_distribution(cls: _D) -> _D:
    """Class decorator: make `cls` reconstructible from a record by its `name`."""
    _REGISTRY[cls.name] = cls
    return cls


def distribution_from_dict(data: Dict[str, Any]) -> "NoiseDistribution":
    """Rebuild a distribution from its `as_dict()` record."""
    name = data.get("name")
    cls = _REGISTRY.get(name)
    if cls is None:
        raise ValueError(
            f"Unknown noise distribution {name!r}; registered: {sorted(_REGISTRY)}."
        )
    return cls(**cls._coerce({k: v for k, v in data.items() if k != "name"}))


def as_profile(value: NoiseProfile | float) -> NoiseProfile:
    """A fresh `NoiseProfile` from a rate or a profile - the one coercion every setter uses.

    Copies the whole profile rather than rebuilding it from `p`, so a field added to
    `NoiseProfile` later is never silently dropped on the way onto a chip.
    """
    return value.copy() if isinstance(value, NoiseProfile) else NoiseProfile(float(value))


def profiles(keys: Iterable, rates: Iterable[float]) -> Dict[Any, NoiseProfile]:
    """One fresh `NoiseProfile` per key; the single place a producer builds its output."""
    return {k: NoiseProfile(float(p)) for k, p in zip(keys, rates)}


def _fresh_seed() -> int:
    return SeedSequence().entropy


@dataclass(repr=False)
class NoiseDistribution(ABC):
    """
    A recipe for a PER landscape: parameters, a seed, and the two producers.

    `seed` is resolved at construction (a fresh one when None and the distribution is
    randomized), so the object always carries the seed it will use and `as_dict()` is a
    complete, replayable record. Equality is by recipe - parameters and seed.
    """

    name: ClassVar[str]
    randomized: ClassVar[bool] = True
    seed: Optional[int] = field(default=None, kw_only=True)

    def __post_init__(self) -> None:
        if self.randomized and self.seed is None:
            self.seed = _fresh_seed()

    def __repr__(self) -> str:
        args = ", ".join(f"{k}={v!r}" for k, v in self.as_dict().items() if k != "name")
        return f"{type(self).__name__}({args})"

    # ------------------------------------------------------------------
    # Recipe
    # ------------------------------------------------------------------
    @property
    def params(self) -> Dict[str, Any]:
        """Every field except `seed`, positional ones first."""
        declared = [f for f in dataclass_fields(self) if f.name != "seed"]
        ordered = [f for f in declared if not f.kw_only] + [f for f in declared if f.kw_only]
        return {f.name: getattr(self, f.name) for f in ordered}

    def as_dict(self) -> Dict[str, Any]:
        """The flat `{name, **params, seed}` record display surfaces and flakes read."""
        flat: Dict[str, Any] = {"name": self.name, **self.params}
        if self.seed is not None:
            flat["seed"] = self.seed
        return flat

    @staticmethod
    def from_dict(data: Dict[str, Any]) -> "NoiseDistribution":
        return distribution_from_dict(data)

    @classmethod
    def _coerce(cls, kwargs: Dict[str, Any]) -> Dict[str, Any]:
        """Hook for subclasses whose fields lose type through JSON (tuples -> lists)."""
        return kwargs

    # ------------------------------------------------------------------
    # Production
    # ------------------------------------------------------------------
    @abstractmethod
    def sites(self, chip: "Chip") -> Dict[Coord, NoiseProfile]:
        """A noise profile for every site of `chip`."""

    @abstractmethod
    def couplers(
        self, chip: "Chip", *, correlation: Optional[float] = None
    ) -> Dict[CouplerKey, NoiseProfile]:
        """A profile for every coupler of `chip`.

        `correlation` ties the coupler landscape to the site landscape the chip currently
        holds; only distributions built on a Gaussian field can honour it.
        """

    def _reject_correlation(self, correlation: Optional[float]) -> None:
        if correlation is not None:
            raise ValueError(
                f"{type(self).__name__} has no Gaussian field, so it cannot be "
                f"cross-correlated with the sites (correlation={correlation})."
            )


# ----------------------------------------------------------------------
# Distributions without a Gaussian field
# ----------------------------------------------------------------------


@register_distribution
@dataclass(repr=False)
class Uniform(NoiseDistribution):
    """Every site (or coupler) at the same rate `p`."""

    name: ClassVar[str] = "uniform homogeneous"
    randomized: ClassVar[bool] = False
    p: float

    def sites(self, chip: "Chip") -> Dict[Coord, NoiseProfile]:
        keys = list(chip.noise_map.keys())
        return profiles(keys, [self.p] * len(keys))

    def couplers(
        self, chip: "Chip", *, correlation: Optional[float] = None
    ) -> Dict[CouplerKey, NoiseProfile]:
        self._reject_correlation(correlation)
        keys = list(chip.coupler_map.keys())
        return profiles(keys, [self.p] * len(keys))


@register_distribution
@dataclass(repr=False)
class Custom(NoiseDistribution):
    """
    Explicit maps supplied by the caller (floats or profiles), e.g. measured rates.

    The maps are not part of the record - a flake stores the rates themselves - so
    `as_dict()` is the name alone and a restored `Custom` carries no maps. Equality is
    therefore by name only.
    """

    name: ClassVar[str] = "custom"
    randomized: ClassVar[bool] = False
    noise_map: Optional[Dict[Coord, Any]] = field(default=None, compare=False, repr=False)
    coupler_map: Optional[Dict[CouplerKey, Any]] = field(
        default=None, compare=False, repr=False
    )

    @property
    def params(self) -> Dict[str, Any]:
        return {}

    def sites(self, chip: "Chip") -> Dict[Coord, NoiseProfile]:
        if self.noise_map is None:
            raise ValueError("This Custom distribution carries no site map.")
        return {c: as_profile(n) for c, n in self.noise_map.items()}

    def couplers(
        self, chip: "Chip", *, correlation: Optional[float] = None
    ) -> Dict[CouplerKey, NoiseProfile]:
        self._reject_correlation(correlation)
        if self.coupler_map is None:
            raise ValueError("This Custom distribution carries no coupler map.")
        return {e: as_profile(n) for e, n in self.coupler_map.items()}


# ----------------------------------------------------------------------
# Distributions built on a Gaussian field
# ----------------------------------------------------------------------


@dataclass(repr=False)
class GaussianFieldDistribution(NoiseDistribution):
    """
    A landscape built in two steps: a Gaussian field that carries only spatial
    structure (`_gaussian_field`), then a reshaping of its values into the requested
    marginal (`_to_rates`). Subclasses fill those two hooks and inherit sites, couplers,
    and the cross-correlated coupler path.

    Couplers read the field at their two endpoints (the field lives on sites). With a
    `correlation` ρ the coupler latent is `ρ·A + √(1−ρ²)·B` - `A` the normal scores of
    the endpoint-mean site rates the chip currently holds, `B` the field's endpoint
    means - so ρ is exactly the correlation between a coupler and its endpoint-mean
    latent (the linear model of coregionalization). ρ = 1 reproduces the ordering
    `derive_coupler_noise("mean")` gives; ρ = 0 ignores the sites entirely.
    """

    @abstractmethod
    def _gaussian_field(self, chip: "Chip") -> Dict[Coord, float]:
        """One Gaussian number per site, carrying only spatial structure."""

    @abstractmethod
    def _to_rates(self, values: np.ndarray) -> np.ndarray:
        """Gaussian numbers -> error rates with the requested marginal, order preserved."""

    def sites(self, chip: "Chip") -> Dict[Coord, NoiseProfile]:
        field_ = self._gaussian_field(chip)
        return profiles(field_.keys(), self._to_rates(np.fromiter(field_.values(), float)))

    def _uncorrelated_couplers(self, chip: "Chip") -> Dict[CouplerKey, NoiseProfile]:
        """Couplers from the field alone; the branch taken when no correlation is asked."""
        field_ = self._gaussian_field(chip)
        couplers = chip.couplers
        own = [mean(field_[e] for e in c.ends) for c in couplers]
        return profiles([c.ends for c in couplers], self._to_rates(np.asarray(own)))

    def couplers(
        self, chip: "Chip", *, correlation: Optional[float] = None
    ) -> Dict[CouplerKey, NoiseProfile]:
        if correlation is None:
            return self._uncorrelated_couplers(chip)
        couplers = chip.couplers
        site_latent = normal_scores(
            [mean(chip.loc(e).noise.p for e in c.ends) for c in couplers]
        )
        field_ = self._gaussian_field(chip)
        own_latent = [mean(field_[e] for e in c.ends) for c in couplers]
        latent = blend_latents(site_latent, own_latent, correlation)
        return profiles([c.ends for c in couplers], self._to_rates(latent))


@dataclass(repr=False)
class _IIDDistribution(GaussianFieldDistribution):
    """
    Shared shape of the two independent-draw distributions.

    Plain output keeps scipy `rvs` draws, one per entry in chip order and rounded to
    five decimals, exactly as the original generators did, so a recorded seed
    reproduces the identical chip. The Gaussian-field path (`_gaussian_field` +
    `_to_rates`) is only taken when a coupler correlation is requested; it draws from
    the same marginal by inverse transform.
    """

    def _target(self):
        raise NotImplementedError

    def _draw(self, n: int) -> list:
        rng = default_rng(self.seed)
        dist = self._target()
        return [round(dist.rvs(1, random_state=rng)[0], 5) for _ in range(n)]

    def sites(self, chip: "Chip") -> Dict[Coord, NoiseProfile]:
        keys = list(chip.noise_map.keys())
        return profiles(keys, self._draw(len(keys)))

    def _uncorrelated_couplers(self, chip: "Chip") -> Dict[CouplerKey, NoiseProfile]:
        keys = list(chip.coupler_map.keys())
        return profiles(keys, self._draw(len(keys)))

    def _gaussian_field(self, chip: "Chip") -> Dict[Coord, float]:
        return iid_gaussian_field(chip, self.seed)

    def _to_rates(self, values: np.ndarray) -> np.ndarray:
        return quantile_map(values, self._target())


@register_distribution
@dataclass(repr=False)
class RandomUniform(_IIDDistribution):
    """Independent draws from a uniform distribution over `bounds = (low, high)`."""

    name: ClassVar[str] = "uniform random"
    bounds: Tuple[float, float]

    @classmethod
    def _coerce(cls, kwargs: Dict[str, Any]) -> Dict[str, Any]:
        if "bounds" in kwargs:
            kwargs = {**kwargs, "bounds": tuple(kwargs["bounds"])}
        return kwargs

    def _target(self):
        low, high = self.bounds
        return uniform(loc=low, scale=high - low)


@register_distribution
@dataclass(repr=False)
class RandomGaussian(_IIDDistribution):
    """Independent draws from a normal distribution truncated to the admissible range."""

    name: ClassVar[str] = "gaussian"
    mean: float
    deviation: float

    def _target(self):
        floor, _ = p_bounds()
        return truncnorm(
            (floor - self.mean) / self.deviation,
            (1 - self.mean) / self.deviation,
            loc=self.mean,
            scale=self.deviation,
        )


@dataclass(repr=False)
class ContourDistribution(GaussianFieldDistribution):
    """
    A spatially correlated landscape: the field is white noise box-averaged over a
    distance-`slope` tile footprint, so `slope` is the correlation length in unit cells.
    Subclasses choose the reshape.
    """

    slope: int = field(default=5, kw_only=True)

    @abstractmethod
    def _white_noise(self) -> Tuple[float, float]:
        """`(mean, deviation)` of the white noise the field is averaged from."""

    def _gaussian_field(self, chip: "Chip") -> Dict[Coord, float]:
        mean_, deviation = self._white_noise()
        return correlated_gaussian_field(chip, mean_, deviation, self.seed, self.slope)


@register_distribution
@dataclass(repr=False)
class NormalContour(ContourDistribution):
    """The original derived contour: a Gaussian-shaped correlated landscape."""

    name: ClassVar[str] = "derived contour"
    mean: float
    deviation: float

    def _white_noise(self) -> Tuple[float, float]:
        return self.mean, self.deviation

    def _to_rates(self, values: np.ndarray) -> np.ndarray:
        return scale_gaussian_contour(values, self.deviation)


@register_distribution
@dataclass(repr=False)
class SkewContour(ContourDistribution):
    """
    A correlated landscape with a skewed (Pearson III) marginal.

    `skew > 0` is right-skewed (a long tail of bad qubits), `skew == 0` is normal.
    `location` pins the mean, or the median with `center="median"`. Same seed and slope
    as `NormalContour` give the same peaks and valleys; only the values differ.
    """

    name: ClassVar[str] = "skewed contour"
    location: float
    deviation: float
    skew: float = 0.0
    center: Center = "mean"

    def _white_noise(self) -> Tuple[float, float]:
        return self.location, self.deviation

    def _to_rates(self, values: np.ndarray) -> np.ndarray:
        return quantile_map(
            values, skewed_target(self.location, self.deviation, self.skew, center=self.center)
        )
