name: Tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install package with test dependencies
        run: pip install -e ".[test]"

      - name: Run tests
        run: pytest --cov=qsnow --cov-report=xml:coverage.xml --junitxml=pytest.xml

      - name: Publish report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Pytest Results
          path: ./pytest.xml
          reporter: java-junit 
